project:
  type: website

website:
  title: "PsychGen Wiki"
  navbar:
    background: primary
    left:
      - text: "Data dictionary"
      - text: "PsychGen Wiki"
<<<<<<< HEAD
=======
        href: about.qmd
>>>>>>> 42bf059e1e333e4a8b5d04bb5519e5ecac55a2fe
      - text: "TSD"
        href: tsd.qmd
      - text: "New analytic project"
        href: new_analytic.qmd
      - text: "Phenotypic data"
        href: pheno.qmd
      - text: "Genetic data"
        href: geno.qmd
      - text: "MoBa"
        href: moba.qmd
    right:
      - text: "Troubleshooting"
        href: trouble.qmd
    tools:
      - icon: github
        menu: 
          - text: Source Code
            href: https://github.com/amslala/psychgen-test
            target: _blank
            
  sidebar:
    - title: "TSD"
      style: "docked"
      background: light
      contents: 
        - tsd.qmd
        - tsd_1.qmd
        - tsd_2.qmd
        - tsd_3.qmd
        - tsd_export.qmd
        - colossus.qmd
    - title: "Phenotypic data"
      contents: 
        - pheno.qmd
        - pheno_1.qmd
        - pheno_2.qmd
        - pheno_3.qmd
    - title: "Genetic data"
      contents: 
        - geno.qmd
        - geno_1.qmd
        - geno_2.qmd

  page-footer:
    background: light 
    right: This website is built with {{< fa heart title="a heart" >}}, [{{< fa brands r-project title="R Project" >}}](https://www.r-project.org/about.html){target=_blank} and [Quarto](https://quarto.org/){target=_blank}
      
format:
  html:
    theme: 
      - flatly
      - styles.scss
    toc: true
    page-layout: full
    mainfont: Cabin
    smooth-scroll: true

editor: visual

execute:
  freeze: auto