project:
  type: website

website:
  title: "PsychGen Hub"
  navbar:
    background: primary
    left:
      - text: "Data dictionary"
      - text: "PsychGen Wiki"
      - text: "TSD"
        href: psychgen_wiki/tsd.qmd
      - text: "New analytic project"
        href: psychgen_wiki/new_analytic.qmd
      - text: "Phenotypic data"
        href: psychgen_wiki/pheno.qmd
      - text: "Genetic data"
        href: psychgen_wiki/geno.qmd
      - text: "MoBa"
        href: psychgen_wiki/moba.qmd
    right:
      - text: "Troubleshooting"
        href: psychgen_wiki/trouble.qmd
    tools:
      - icon: github
        menu: 
          - text: Source Code
            href: https://github.com/amslala/psychgen-test
            target: _blank
            
  sidebar:
    - title: "TSD"
      style: "docked"
      background: light
      contents: 
        - psychgen_wiki/tsd.qmd
        - psychgen_wiki/tsd_1.qmd
        - psychgen_wiki/tsd_2.qmd
        - psychgen_wiki/tsd_3.qmd
        - psychgen_wiki/tsd_export.qmd
        - psychgen_wiki/colossus.qmd
    - title: "Phenotypic data"
      contents: 
        - pheno.qmd
        - pheno_1.qmd
        - pheno_2.qmd
        - pheno_3.qmd
    - title: "Genetic data"
      contents: 
        - geno.qmd
        - geno_1.qmd
        - geno_2.qmd

  page-footer:
    background: light 
    right: This website is built with {{< fa heart title="a heart" >}}, [{{< fa brands r-project title="R Project" >}}](https://www.r-project.org/about.html){target=_blank} and [Quarto](https://quarto.org/){target=_blank}
      
format:
  html:
    theme: 
      - flatly
      - styles.scss
    toc: true
    page-layout: full
    mainfont: Cabin
    smooth-scroll: true

editor: visual

execute:
  freeze: auto