project:
  type: website

website:
  title: false
  page-navigation: true
  back-to-top-navigation: true
  
  navbar:
    background: primary
    collapse-bellow: lg
    left:
      - text: "PsychGen Hub"
        href: about.qmd
      - text: "Data dictionary"
      - text: "PsychGen Wiki"
        href: docs/psychgen_wiki/data_gettingstarted.qmd
      - text: "Teams"
      - text: "PsychGen Github"
    tools:
      - icon: github
        menu: 
          - text: "Edit this page: Source Code"
            href: https://github.com/amslala/psychgen-test
            target: _blank
            
  sidebar:
    - id: psychgen_wiki
    - title: "PsychGen Wiki"
      style: "docked"
      align: left
      contents: 
        - "---"
        - section: "Data analysis in p471"
          contents: 
            - text: "Getting started"
              href: docs/psychgen_wiki/data_gettingstarted.qmd
            - section: "Using TSD"
              contents: 
                - href: docs/psychgen_wiki/tsd_gettingstarted.qmd
                - text: "Setting up a new analytical project and Git"
                  href: docs/psychgen_wiki/git.qmd
            - text: "Using HPC"
              href: docs/psychgen_wiki/using_hpc.qmd
        - "---"
        - section: "Exports, publications and preregistration"
          contents: 
            - text: "Preregistration"
              href: docs/psychgen_wiki/preregistration.qmd
            - text: "Export templates"
              href: docs/psychgen_wiki/export.qmd
            - text: "Publication checklist"
              href: docs/psychgen_wiki/checklist.qmd
        - "---"
        - section: "Other resources"
          contents: 
            - text: "Logos"
              href: docs/psychgen_wiki/logos.qmd
            - text: "Reporting to CRISTIN"
              href: docs/psychgen_wiki/ReportingCristin.qmd 
          
          
  page-footer:
    background: light 
    right: This website is built with {{< fa heart title="a heart" >}}, [{{< fa brands r-project title="R Project" >}}](https://www.r-project.org/about.html){target=_blank} and [Quarto](https://quarto.org/){target=_blank}
      
format:
  html:
    theme: 
      - flatly
      - styles.scss
    toc: true
    page-layout: full
    mainfont: Cabin
    smooth-scroll: true
    grid: 
      sidebar-width: 250px
      body-width: 900px
      margin-width: 300px

editor: visual

execute:
  freeze: auto